### ISSUE TITLE
Hyperdrive not installing Lando on Ubuntu 20.04 

### ISSUE THREAD

**Issue by signosis** [lando/hyperdrive#21]
**Describe the bug**
Lando is not being installed on Ubuntu 20.04.  The install script shows Lando being installed but when running the script again to check it shows Lando not installed.

**To Reproduce**
1.  Freshly installed Ubuntu 20.04 with updates
2. curl -Ls https://github.com/lando/hyperdrive/releases/download/v0.6.1/hyperdrive > /tmp/hyperdrive \
  && chmod +x /tmp/hyperdrive \
  && /tmp/hyperdrive
3. Script says Lando is installed
4. Run Script again, says Lando needs to be installed.

**Error #1**
 ```
_    _                          _      _
 | |  | |                        | |    (_)
 | |__| |_   _ _ __   ___ _ __ __| |_ __ ___   _____
 |  __  | | | | '_ \ / _ \ '__/ _` | '__| \ \ / / _ \
 | |  | | |_| | |_) |  __/ | | (_| | |  | |\ V /  __/
 |_|  |_|\__, | .__/ \___|_|  \__,_|_|  |_| \_/ \___|
          __/ | |
         |___/|_|

Determining operating system .................................. ubuntu
Determining package manager .................................. aptitude
Determining curl version .................................. 7.68.0
Determining git version .................................. 2.25.1
Checking for git config user name .................................. support
Checking for git config user email .................................. support@******
Determining node version .................................. 12.22.1
Determining yarn version .................................. 1.22.5
Determining docker version .................................. 20.10.6
Determining lando version .................................. not installed
Checking for ssh public key .................................. support@*********
Reticulating .................................. done!

Computing results matrix .................................. done!

THING     CURRENT VERSION/STATUS  RECOMMENDED ACTION
os
pkgmgr
curl
git
gitname
gitemail
node
yarn
docker
lando
sshkey

NOW I WANT TO ASK YOU A BUNCH OF QUESTIONS AND I WANT TO HAVE THEM ANSWERED IMMEDIATELY!

Do you wish for this script to take the recommended actions marked above? [Y/n]

Downloading Lando
############################################################################ 100.0%
(Reading database ... 73284 files and directories currently installed.)
Preparing to unpack /tmp/lando.deb ...
Unpacking lando (3.1.2) over (3.1.2) ...
Setting up lando (3.1.2) ...
+ LANDO_ROOT=/usr/share/lando
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/bin
+ TERM=xterm
+ chmod 755 -R /usr/share/lando
+ mkdir -p /usr/local/bin
+ ln -sf /usr/share/lando/bin/lando /usr/local/bin/lando
++ awk -F: '$1 == "sudo" {print $4}' /etc/group
+ SUDOERS=support
+ for u in ${SUDOERS//,/ }
+ usermod -a -G docker support
+ MAX_MAP_COUNT=262144
+ MMC_PARAMETER_PATH=/proc/sys/vm/max_map_count
+ '[' -f /proc/sys/vm/max_map_count ']'
++ sysctl -n vm.max_map_count
+ '[' 262144 -lt 262144 ']'
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Installation complete. You have made it into hyperspace!
Please run again if you want to verify installation success.

```
**Error #2**
If I try run Lando afterward I get the following error

```
support@S1-HP-G1-I5:~$ lando
Traceback (most recent call last):
  File "/home/support/.local/bin/lando", line 8, in <module>
    sys.exit(main())
  File "/home/support/.local/lib/python3.8/site-packages/lando/server/__main__.py", line 17, in main
    config = ServerConfig(config_filename)
  File "/home/support/.local/lib/python3.8/site-packages/lando/server/config.py", line 20, in __init__
    with open(filename, 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/lando_config.yml'
```

**Expected behavior**

**Operating System and version:**
Linux S1-HP-G1-I5 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20.04 

On the same system, Ubuntu 18.04 works fine.

**Comment by marklabrecque** [comment]
I was having a similar issue where Ubuntu 20.04 didn't install (but Ubuntu 18.04 did). For me, the problem was that the docker-engine package doesn't exist in the focal repos - instead it appears as though the package has been renamed to docker-ce. If you follow the instructions on the Docker install page for Ubuntu (https://docs.docker.com/engine/install/ubuntu/) and then re-run Hyperdrive, it will properly detect the Docker installation and install the rest of the components without issue. I think the key part is this line:

`sudo apt-get install docker-ce docker-ce-cli containerd.io`

Hope this helps!
